<?php

$surahs = [
    [1, 'الفاتحة', 'Al-Fatiha', 'Открывающая', 'meccan', 7],
    [2, 'البقرة', 'Al-Baqarah', 'Корова', 'medinan', 286],
    [3, 'آل عمران', 'Ali Imran', 'Семейство Имрана', 'medinan', 200],
    [4, 'النساء', 'An-Nisa', 'Женщины', 'medinan', 176],
    [5, 'المائدة', 'Al-Maidah', 'Трапеза', 'medinan', 120],
    [6, 'الأنعام', 'Al-Anam', 'Скот', 'meccan', 165],
    [7, 'الأعراف', 'Al-Araf', 'Ограды', 'meccan', 206],
    [8, 'الأنفال', 'Al-Anfal', 'Трофеи', 'medinan', 75],
    [9, 'التوبة', 'At-Tawbah', 'Покаяние', 'medinan', 129],
    [10, 'يونس', 'Yunus', 'Йунус', 'meccan', 109],
    [11, 'هود', 'Hud', 'Худ', 'meccan', 123],
    [12, 'يوسف', 'Yusuf', 'Йусуф', 'meccan', 111],
    [13, 'الرعد', 'Ar-Rad', 'Гром', 'medinan', 43],
    [14, 'إبراهيم', 'Ibrahim', 'Ибрахим', 'meccan', 52],
    [15, 'الحجر', 'Al-Hijr', 'Хиджр', 'meccan', 99],
    [16, 'النحل', 'An-Nahl', 'Пчёлы', 'meccan', 128],
    [17, 'الإسراء', 'Al-Isra', 'Ночной перенос', 'meccan', 111],
    [18, 'الكهف', 'Al-Kahf', 'Пещера', 'meccan', 110],
    [19, 'مريم', 'Maryam', 'Марьям', 'meccan', 98],
    [20, 'طه', 'Taha', 'Та Ха', 'meccan', 135],
    [21, 'الأنبياء', 'Al-Anbiya', 'Пророки', 'meccan', 112],
    [22, 'الحج', 'Al-Hajj', 'Паломничество', 'medinan', 78],
    [23, 'المؤمنون', 'Al-Muminun', 'Верующие', 'meccan', 118],
    [24, 'النور', 'An-Nur', 'Свет', 'medinan', 64],
    [25, 'الفرقان', 'Al-Furqan', 'Различение', 'meccan', 77],
    [26, 'الشعراء', 'Ash-Shuara', 'Поэты', 'meccan', 227],
    [27, 'النمل', 'An-Naml', 'Муравьи', 'meccan', 93],
    [28, 'القصص', 'Al-Qasas', 'Рассказ', 'meccan', 88],
    [29, 'العنكبوت', 'Al-Ankabut', 'Паук', 'meccan', 69],
    [30, 'الروم', 'Ar-Rum', 'Римляне', 'meccan', 60],
    [31, 'لقمان', 'Luqman', 'Лукман', 'meccan', 34],
    [32, 'السجدة', 'As-Sajdah', 'Поклон', 'meccan', 30],
    [33, 'الأحزاب', 'Al-Ahzab', 'Союзники', 'medinan', 73],
    [34, 'سبأ', 'Saba', 'Саба', 'meccan', 54],
    [35, 'فاطر', 'Fatir', 'Творец', 'meccan', 45],
    [36, 'يس', 'Ya-Sin', 'Йа Син', 'meccan', 83],
    [37, 'الصافات', 'As-Saffat', 'Выстроившиеся', 'meccan', 182],
    [38, 'ص', 'Sad', 'Сад', 'meccan', 88],
    [39, 'الزمر', 'Az-Zumar', 'Толпы', 'meccan', 75],
    [40, 'غافر', 'Ghafir', 'Прощающий', 'meccan', 85],
    [41, 'فصلت', 'Fussilat', 'Разъяснены', 'meccan', 54],
    [42, 'الشورى', 'Ash-Shura', 'Совет', 'meccan', 53],
    [43, 'الزخرف', 'Az-Zukhruf', 'Украшения', 'meccan', 89],
    [44, 'الدخان', 'Ad-Dukhan', 'Дым', 'meccan', 59],
    [45, 'الجاثية', 'Al-Jathiyah', 'Коленопреклонённые', 'meccan', 37],
    [46, 'الأحقاف', 'Al-Ahqaf', 'Пески', 'meccan', 35],
    [47, 'محمد', 'Muhammad', 'Мухаммад', 'medinan', 38],
    [48, 'الفتح', 'Al-Fath', 'Победа', 'medinan', 29],
    [49, 'الحجرات', 'Al-Hujurat', 'Комнаты', 'medinan', 18],
    [50, 'ق', 'Qaf', 'Каф', 'meccan', 45],
    [51, 'الذاريات', 'Adh-Dhariyat', 'Рассеивающие', 'meccan', 60],
    [52, 'الطور', 'At-Tur', 'Гора', 'meccan', 49],
    [53, 'النجم', 'An-Najm', 'Звезда', 'meccan', 62],
    [54, 'القمر', 'Al-Qamar', 'Луна', 'meccan', 55],
    [55, 'الرحمن', 'Ar-Rahman', 'Милостивый', 'medinan', 78],
    [56, 'الواقعة', 'Al-Waqiah', 'Событие', 'meccan', 96],
    [57, 'الحديد', 'Al-Hadid', 'Железо', 'medinan', 29],
    [58, 'المجادلة', 'Al-Mujadilah', 'Препирательство', 'medinan', 22],
    [59, 'الحشر', 'Al-Hashr', 'Сбор', 'medinan', 24],
    [60, 'الممتحنة', 'Al-Mumtahanah', 'Испытание', 'medinan', 13],
    [61, 'الصف', 'As-Saff', 'Ряд', 'medinan', 14],
    [62, 'الجمعة', 'Al-Jumuah', 'Пятница', 'medinan', 11],
    [63, 'المنافقون', 'Al-Munafiqun', 'Лицемеры', 'medinan', 11],
    [64, 'التغابن', 'At-Taghabun', 'Взаимное обделение', 'medinan', 18],
    [65, 'الطلاق', 'At-Talaq', 'Развод', 'medinan', 12],
    [66, 'التحريم', 'At-Tahrim', 'Запрещение', 'medinan', 12],
    [67, 'الملك', 'Al-Mulk', 'Власть', 'meccan', 30],
    [68, 'القلم', 'Al-Qalam', 'Письменная трость', 'meccan', 52],
    [69, 'الحاقة', 'Al-Haqqah', 'Неизбежное', 'meccan', 52],
    [70, 'المعارج', 'Al-Maarij', 'Ступени', 'meccan', 44],
    [71, 'نوح', 'Nuh', 'Нух', 'meccan', 28],
    [72, 'الجن', 'Al-Jinn', 'Джинны', 'meccan', 28],
    [73, 'المزمل', 'Al-Muzzammil', 'Закутавшийся', 'meccan', 20],
    [74, 'المدثر', 'Al-Muddaththir', 'Закутавшийся', 'meccan', 56],
    [75, 'القيامة', 'Al-Qiyamah', 'Воскресение', 'meccan', 40],
    [76, 'الإنسان', 'Al-Insan', 'Человек', 'medinan', 31],
    [77, 'المرسلات', 'Al-Mursalat', 'Посылаемые', 'meccan', 50],
    [78, 'النبأ', 'An-Naba', 'Весть', 'meccan', 40],
    [79, 'النازعات', 'An-Naziat', 'Вырывающие', 'meccan', 46],
    [80, 'عبس', 'Abasa', 'Нахмурился', 'meccan', 42],
    [81, 'التكوير', 'At-Takwir', 'Свёртывание', 'meccan', 29],
    [82, 'الانفطار', 'Al-Infitar', 'Раскалывание', 'meccan', 19],
    [83, 'المطففين', 'Al-Mutaffifin', 'Обвешивающие', 'meccan', 36],
    [84, 'الانشقاق', 'Al-Inshiqaq', 'Раскол', 'meccan', 25],
    [85, 'البروج', 'Al-Buruj', 'Созвездия', 'meccan', 22],
    [86, 'الطارق', 'At-Tariq', 'Ночной путник', 'meccan', 17],
    [87, 'الأعلى', 'Al-Ala', 'Всевышний', 'meccan', 19],
    [88, 'الغاشية', 'Al-Ghashiyah', 'Покрывающее', 'meccan', 26],
    [89, 'الفجر', 'Al-Fajr', 'Заря', 'meccan', 30],
    [90, 'البلد', 'Al-Balad', 'Город', 'meccan', 20],
    [91, 'الشمس', 'Ash-Shams', 'Солнце', 'meccan', 15],
    [92, 'الليل', 'Al-Layl', 'Ночь', 'meccan', 21],
    [93, 'الضحى', 'Ad-Duha', 'Утро', 'meccan', 11],
    [94, 'الشرح', 'Ash-Sharh', 'Раскрытие', 'meccan', 8],
    [95, 'التين', 'At-Tin', 'Смоковница', 'meccan', 8],
    [96, 'العلق', 'Al-Alaq', 'Сгусток', 'meccan', 19],
    [97, 'القدر', 'Al-Qadr', 'Предопределение', 'meccan', 5],
    [98, 'البينة', 'Al-Bayyinah', 'Ясное знамение', 'medinan', 8],
    [99, 'الزلزلة', 'Az-Zalzalah', 'Землетрясение', 'medinan', 8],
    [100, 'العاديات', 'Al-Adiyat', 'Мчащиеся', 'meccan', 11],
    [101, 'القارعة', 'Al-Qariah', 'Великое бедствие', 'meccan', 11],
    [102, 'التكاثر', 'At-Takathur', 'Приумножение', 'meccan', 8],
    [103, 'العصر', 'Al-Asr', 'Время', 'meccan', 3],
    [104, 'الهمزة', 'Al-Humazah', 'Хулитель', 'meccan', 9],
    [105, 'الفيل', 'Al-Fil', 'Слон', 'meccan', 5],
    [106, 'قريش', 'Quraysh', 'Курайшиты', 'meccan', 4],
    [107, 'الماعون', 'Al-Maun', 'Мелочь', 'meccan', 7],
    [108, 'الكوثر', 'Al-Kawthar', 'Изобилие', 'meccan', 3],
    [109, 'الكافرون', 'Al-Kafirun', 'Неверующие', 'meccan', 6],
    [110, 'النصر', 'An-Nasr', 'Помощь', 'medinan', 3],
    [111, 'المسد', 'Al-Masad', 'Пальмовые волокна', 'meccan', 5],
    [112, 'الإخلاص', 'Al-Ikhlas', 'Очищение веры', 'meccan', 4],
    [113, 'الفلق', 'Al-Falaq', 'Рассвет', 'meccan', 5],
    [114, 'الناس', 'An-Nas', 'Люди', 'meccan', 6],
];

$stmt = $db->prepare('
    INSERT IGNORE INTO surahs (id, number, name_arabic, name_transliteration, name_translation, revelation_type, ayah_count, bismillah_pre, order_index)
    VALUES (:id, :number, :name_arabic, :name_transliteration, :name_translation, :revelation_type, :ayah_count, :bismillah_pre, :order_index)
');

foreach ($surahs as $s) {
    $stmt->execute([
        'id' => seedUuid(),
        'number' => $s[0],
        'name_arabic' => $s[1],
        'name_transliteration' => $s[2],
        'name_translation' => $s[3],
        'revelation_type' => $s[4],
        'ayah_count' => $s[5],
        'bismillah_pre' => $s[0] !== 9 ? 1 : 0,
        'order_index' => $s[0],
    ]);
}

echo "  Inserted " . count($surahs) . " surahs.\n";
